---
title: "flex"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(datasets)
library(shiny)
library(dplyr)
library(readxl)
library(ggplot2)
library(stringr)
library(plotly)
library(broman)
library(ggpubr)
prisma <- read_excel("prisma.xlsx")
prisam<- na.omit(prisma)
colnames(prisma)<- c("ano_lei", "ano_despesa", "gnd", "exec","uo", "valor")
prisma$ano_lei<- as.numeric(prisma$ano_lei)
prisma$ano_despesa<- as.numeric(prisma$ano_despesa)
prisma<- na.omit(prisma)
prisma<-prisma%>%
  mutate(temporal = ifelse(ano_lei == ano_despesa, "loa", "rp"))


```



Selecione o período {.sidebar}
=======================================================================

###### Ano do empenho do investimento:

```{r}
sliderInput("ano_loa", "",
                        min = min(prisma$ano_lei), max = max(prisma$ano_lei),
                        value = c(min(prisma$ano_lei), max = max(prisma$ano_lei)),
                        step = 1)

```





###### Ano do pagamento do investimento:
```{r}
            
            
            # Input: Decimal interval with step value ----
sliderInput("ano_pgt", "",
                        min = min(prisma$ano_despesa), max = max(prisma$ano_despesa),
                        value = c(min(prisma$ano_despesa), max = max(prisma$ano_despesa)),
                        step = 1)
            
```

Dashboard
=======================================================================

Row
-----------------------------------------------------------------------
```{r}
# dlCount is a reactive expression that keeps track of the total
# number of rows that have ever appeared through pkgStream.

      
     
      
# Emit the download count
renderValueBox({
  
  rp_pg <-  prisma%>%
        filter(ano_lei >=  min(input$ano_loa) & ano_lei <=  max(input$ano_loa),
               ano_despesa >=  min(input$ano_pgt) & ano_despesa <=  max(input$ano_pgt),
               temporal == "rp",
               gnd == "INVESTIMENTOS")%>%
        group_by( temporal)%>%
        summarise(pago=round(sum(valor/1000000000),2))
  
  
  valueBox(rp_pg, icon = "fa-download")
})
```

Row
-----------------------------------------------------------------------

```{r}
# dlCount is a reactive expression that keeps track of the total
# number of rows that have ever appeared through pkgStream.

      
     
      
# Emit the download count
renderValueBox({
  
  loa_pg <-  prisma%>%
        filter(ano_lei >=  min(input$ano_loa) & ano_lei <=  max(input$ano_loa),
               ano_despesa >=  min(input$ano_pgt) & ano_despesa <=  max(input$ano_pgt),
               temporal == "loa",
               gnd == "INVESTIMENTOS")%>%
        group_by( temporal)%>%
        summarise(pago=round(sum(valor/1000000000),2))
  
  
  valueBox(loa_pg, icon = "fa-download")
})
```




Row
-----------------------------------------------------------------------

### Ano do empenho do investimento (R$ bi) 

```{r}
renderPlot({
      prisma_lei<- prisma%>%
        filter(ano_lei >=  min(input$ano_loa) & ano_lei <=  max(input$ano_loa),
               ano_despesa >=  min(input$ano_pgt) & ano_despesa <=  max(input$ano_pgt),
               gnd == "INVESTIMENTOS")%>%
        group_by(ano_lei, temporal)%>%
        summarise(pago=sum(valor/1000000000))
      
     
      
        
      
        ggplot(prisma_lei) +
        
          geom_bar(data=prisma_lei, aes(x = ano_lei, y = pago, fill=temporal ), stat = "identity",  width = .9)+
          guides(fill=FALSE)+
          scale_fill_manual(values = c("loa" = "blue", "rp" = "red"))+
          theme_bw()+
          scale_x_continuous(limits=c(2007,2020), breaks  = c(2008, 2009,2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2017, 2018, 2019))+
          ggtitle("")+
          theme(plot.title=element_text(family='', face='bold', colour='#cc6600', size=11))+
          theme(axis.title.x = element_blank())+
          theme(axis.title.y = element_blank())+
          theme(axis.text.x = element_text(size = 8)) +
          
          theme(
            # Remove panel border
            panel.border = element_blank(),  
            # Remove panel grid lines
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            # Remove panel background
            panel.background = element_blank(),
            # Add axis line
            axis.line = element_line(colour = "grey"),
            legend.position="top"
          )
      
      
      
      
      
      
      
      
      
      
      
    })
```




### Ano do pagamento do investimento (R$ bi) 
```{r}
renderPlot({
      
      
      prisma_pago<- prisma%>%
        filter(ano_lei >=  min(input$ano_loa) & ano_lei <=  max(input$ano_loa),
               ano_despesa >=  min(input$ano_pgt) & ano_despesa <=  max(input$ano_pgt),
               gnd == "INVESTIMENTOS")%>%
        group_by(ano_despesa, temporal)%>%
        select(ano_despesa, temporal, valor)%>%
        summarise(pago=sum(valor/1000000000))
      
      
      ano<-plot_ly(prisma_pago)%>%
        ggplot() +
        geom_bar(data=prisma_pago, aes(x = ano_despesa, y = pago, fill= temporal ), stat = "identity",   width = .9)+
        guides(fill=FALSE)+
        scale_fill_manual(values = c("loa" = "blue", "rp" = "red"))+
        theme_bw()+
        scale_x_continuous(limits=c(2007,2020), breaks  = c(2008, 2009,2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2017, 2018, 2019))+
        ggtitle("")+
        theme(plot.title=element_text(family='', face='bold', colour='#ff0000', size=11))+
        theme(axis.title.x = element_blank())+
        theme(axis.title.y = element_blank())+
        theme(axis.text.x = element_text(size = 8)) + 
        
        theme(
          # Remove panel border
          panel.border = element_blank(),  
          # Remove panel grid lines
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          # Remove panel background
          panel.background = element_blank(),
          # Add axis line
          axis.line = element_line(colour = "grey"),
          legend.position="top"
        )
      
     
      
      ano
      
      
      
      
      
      
    })
```

Dashboard2
=======================================================================